config/routes.rb
Keithmiketom3::Application.routes.draw do

  get "contact_form/new"

  get "contact_form/create"

  devise_for :users
    devise_scope :users do
      get "sign_out", :to => "devise/sessions#destroy"
    end
 
  resources :contact_forms

  resources :illustrations

  resources :welcomes

  resources :galleries

  resources :blogs 
  

    match 'about' => 'welcomes#about'
  
    match 'contact' => 'contact_forms#index'
    match 'contactme' => 'contact_forms#new'
    match 'blog' => 'blogs#index'
    match 'art' => 'galleries#index'
    match  'home' => 'parallax#homepage'
    match 'althome' => 'parallax#home'

    

  root :to => 'parallax#homepage'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  attr_accessible :author, :content, :date, :image_url, :title
  has_many :comments, :dependent => :destroy
  
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :author, :blog_id, :content, :email, :subject
  belongs_to :blog 

end

app/models/contact_form.rb
class ContactForm < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i

  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "New Website Email from #{name}",
      :to => "keithmiketom@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  attr_accessible :caption, :date_added, :image_url, :description, :image, :gallery
  has_many :illustrations
end

app/models/illustration.rb
class Illustration < ActiveRecord::Base
  attr_accessible :gallery_id, :image, :caption
  belongs_to :gallery
  mount_uploader :image, ImageUploader
  
  validates :gallery_id, :image, :caption, :presence => true
end

app/models/message.rb
class Message

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :firstname, :lastname, :email, :subject, :comments

  validates :firstname, :lastname, :email, :subject, :comments, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username
  # attr_accessible :title, :body
end

app/models/welcome.rb
class Welcome < ActiveRecord::Base
  attr_accessible :email, :subject, :name, :message
  # attr_accessible :title, :body
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
    @title = "Art Blog"
    @blogs = Blog.order('date DESC')
    @blogs = @blogs.paginate(:page => params[:page], :per_page => 5)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @blogs }
    end
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @blog = Blog.find(params[:id])
    @title = @blog.title
    @comments = Comment.all

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @blog }
    end
  end

  # GET /blogs/new
  # GET /blogs/new.json
  def new
    @blog = Blog.new
    @title = "Create a New Blog Post"

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @blog }
    end
  end

  # GET /blogs/1/edit
  def edit
    @blog = Blog.find(params[:id])
    @title = "Editing Post"
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(params[:blog])
    @title = "Create a New Blog Post"

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render json: @blog, status: :created, location: @blog }
      else
        format.html { render action: "new" }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /blogs/1
  # PUT /blogs/1.json
  def update
    @blog = Blog.find(params[:id])

    respond_to do |format|
      if @blog.update_attributes(params[:blog])
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < InheritedResources::Base
  def new
    @comment = Comment.new
    @title = "create new comment"
  end
  
  def create
    @comment = Comment.new(params[:comment])
    if @comment.save
      redirect_to root_path
    else
      render 'new'
    
      
   end 
  end
  
  def update
    @comment = Comment.find(params[:id])
    @blog = @comment.article
    @title = "Update a Comment"
    redirect_to @blog
    
    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to(@blog, :notice => 'Comment was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end
  
  
  def destroy
    @comment = Comment.find(params[:id])
    @blog = Blog.find(params[:blog_id])
    @comment.destroy
    redirect_to @blog

    respond_to do |format|
      format.html { redirect_to(@blog, :notice => 'Comment was successfully deleted.') }
    end
  end
end

app/controllers/illustrations_controller.rb
class IllustrationsController < ApplicationController
  
  def create
    @illustration = Illustration.new(params[:illustration])

    respond_to do |format|
      if @illustration.save
        format.html { redirect_to @illustration.gallery, notice: 'Illustration was successfully created.' }
        format.json { render json: @illustration.gallery, status: :created, location: @gallery }
      else
        format.html { redirect_to @illustration.gallery, notice: 'Illustration was not saved.' }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @illustration = Illustration.find(params[:id])
    @gallery = @illustration.gallery
    @illustration.destroy

    respond_to do |format|
      format.html { redirect_to @gallery }
      format.json { head :no_content }
    end
  end
end

app/controllers/parallax_controller.rb
class ParallaxController < ApplicationController
  
  layout "home"
  
  def home
    @title = "Welcome to the site"
    respond_to do |format|
      format.html # index.html.erb
    end
  end


  def homepage
    @title = "Welcome to the site"
    respond_to do |format|
      format.html # index.html.erb
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_form_helper.rb
module ContactFormHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
  
end

app/helpers/illustraions_helper.rb
module IllustraionsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/parallax_helper.rb
module ParallaxHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/illustrations/_form.html.erb
<%= form_for @illustration, :html =>{:multipart => true} do |f| %>
  <% if @gallery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>

      <ul>
      <% @gallery.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div>
  
  <div class="field">
    <%= f.label :caption %><br />
    <%= f.text_field :caption %>
  </div>

  <div class="field">
    <%= f.label :gallery_id %><br />
    <%= f.hidden_field :gallery_id %>
  </div>
  
  <div class="actions">
    <%= f.submit "Add to Gallery" %>
  </div>
<% end %>

app/views/illustrations/edit.html.erb
<h1>Editing gallery</h1>

<%= render 'form' %>

<%= link_to 'Show', @gallery %> |
<%= link_to 'Back', galleries_path %>

app/views/illustrations/index.html.erb
<h1>Artwork</h1>
<article id="divbox">
<% @galleries.each do |gallery| %>
<div class="gal_thumb">
	<%= link_to image_tag(gallery.image_url, :alt => gallery.caption, :id => gallery.caption.gsub(/\s+/, "").downcase), gallery, :title =>gallery.caption %><!--thumbnail-->
	

<div class="details">
		<strong><%= gallery.caption %></strong><br />
		<em><%= gallery.date_added.strftime('%d/%m/%Y') %></em>
	</div><!--end of details-->
</div><!--end of gal_thumb-->
<% end %>
<!--if admin-->
</article>
<aside id="gallside"><!--stylise accordian jQuery-->
	<% @galleries.each do |gallery| %>
		<h3><%= gallery.caption %></h3>
		<p><%= gallery.description %></p>
	<% end %>
<%= link_to 'New Gallery', new_gallery_path %>
</aside><!--end of add_gal-->

app/views/illustrations/new.html.erb
<h1>New gallery</h1>

<%= render 'form' %>

<%= link_to 'Back', galleries_path %>

app/views/illustrations/show.html.erb
<p id="notice"><%= notice %></p>
<!--this shows individual gallery contents-->
<div class="main">

	<div class="gallery_holder">
		<!-- put loop here for gallery contents-->
		<!-- for each gallery load the images related to that gallery in thumbanil form wrapped in a lightbox rel -->
		<!-- Each image should have a caption -->
		<% @gallery.illustrations.each do |illustration| %>
		
		<div>
			<a href="" rel="lightbox[galleryname]">
				<img src="<%= illustration.image %>" width="150px" alt="thumbnail" />
			</a>
			
			<span><%= illustration.caption%></span>
		</div>
		
		<% end %>
	</div>
	
	<div class="sbar">
		<p>For Admin this is an image uploader</p>
		</div>
	<aside class="detailbox clearfix">
		<h3><%= @title %></h3>
		<p><%= @gallery.description %></p>
		<br />
		<br />
		<br />
		<!--admin only-->
		<!--Image uploader-->
			<div class="gal_admin clearfix">
				
				
    			<%= link_to 'Back', galleries_path %>
				<%= link_to 'Edit', edit_gallery_path(@gallery) %> 
				<%= link_to 'Destroy', @gallery, method: :delete, data: { confirm: 'Are you sure?' } %>
			</div>
	</aside><!--image uploader for admin should go here-->
</div>