config/routes.rb
Keithmiketom3::Application.routes.draw do

  get "contact_form/new"

  get "contact_form/create"

  devise_for :users
    devise_scope :users do
      get "sign_out", :to => "devise/sessions#destroy"
    end
 
  resources :contact_forms

  resources :illustrations

  resources :welcomes

  resources :galleries

  resources :blogs 
  

    match 'about' => 'welcomes#about'
  
    match 'contact' => 'contact_forms#index'
    match 'contactme' => 'contact_forms#new'
    match 'blog' => 'blogs#index'
    match 'art' => 'galleries#index'
    match  'home' => 'parallax#homepage'
    match 'althome' => 'parallax#home'

    

  root :to => 'parallax#homepage'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  attr_accessible :author, :content, :date, :image_url, :title
  has_many :comments, :dependent => :destroy
  
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :author, :blog_id, :content, :email, :subject
  belongs_to :blog 

end

app/models/contact_form.rb
class ContactForm < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i

  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "New Website Email from #{name}",
      :to => "keithmiketom@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  attr_accessible :caption, :date_added, :image_url, :description, :image, :gallery
  has_many :illustrations
end

app/models/illustration.rb
class Illustration < ActiveRecord::Base
  attr_accessible :gallery_id, :image, :caption
  belongs_to :gallery
  mount_uploader :image, ImageUploader
  
  validates :gallery_id, :image, :caption, :presence => true
end

app/models/message.rb
class Message

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :firstname, :lastname, :email, :subject, :comments

  validates :firstname, :lastname, :email, :subject, :comments, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username
  # attr_accessible :title, :body
end

app/models/welcome.rb
class Welcome < ActiveRecord::Base
  attr_accessible :email, :subject, :name, :message
  # attr_accessible :title, :body
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
    @title = "Art Blog"
    @blogs = Blog.order('date DESC')
    @blogs = @blogs.paginate(:page => params[:page], :per_page => 5)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @blogs }
    end
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @blog = Blog.find(params[:id])
    @title = @blog.title
    @comments = Comment.all

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @blog }
    end
  end

  # GET /blogs/new
  # GET /blogs/new.json
  def new
    @blog = Blog.new
    @title = "Create a New Blog Post"

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @blog }
    end
  end

  # GET /blogs/1/edit
  def edit
    @blog = Blog.find(params[:id])
    @title = "Editing Post"
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(params[:blog])
    @title = "Create a New Blog Post"

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render json: @blog, status: :created, location: @blog }
      else
        format.html { render action: "new" }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /blogs/1
  # PUT /blogs/1.json
  def update
    @blog = Blog.find(params[:id])

    respond_to do |format|
      if @blog.update_attributes(params[:blog])
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < InheritedResources::Base
  def new
    @comment = Comment.new
    @title = "create new comment"
  end
  
  def create
    @comment = Comment.new(params[:comment])
    if @comment.save
      redirect_to root_path
    else
      render 'new'
    
      
   end 
  end
  
  def update
    @comment = Comment.find(params[:id])
    @blog = @comment.article
    @title = "Update a Comment"
    redirect_to @blog
    
    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to(@blog, :notice => 'Comment was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end
  
  
  def destroy
    @comment = Comment.find(params[:id])
    @blog = Blog.find(params[:blog_id])
    @comment.destroy
    redirect_to @blog

    respond_to do |format|
      format.html { redirect_to(@blog, :notice => 'Comment was successfully deleted.') }
    end
  end
end

app/controllers/parallax_controller.rb
class ParallaxController < ApplicationController
  
  layout "home"
  
  def home
    @title = "Welcome to the site"
    respond_to do |format|
      format.html # index.html.erb
    end
  end


  def homepage
    @title = "Welcome to the site"
    respond_to do |format|
      format.html # index.html.erb
    end
  end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
 layout "application"
 

  def about
    @title = "About This Site"
    respond_to do |format|
      format.html # index.html.erb
    end
  end
    
  def contact
    @title = "Contact Keith"
    
    
    respond_to do |format|
      format.html # index.html.erb
    end
  def new
    @message = Message.new
    @contact = Message.new
  end

  def create
    @message = Message.new(params[:message])
    @contact = Message.new(params[:message])
    
    if @contact.valid?
      NotificationsMailer.new_message(@contact).deliver
      redirect_to(root_path, :notice => "Message was successfully sent.")
    else
      flash.now.alert = "Please fill all fields."
      render :new
    end
  end
  

  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_form_helper.rb
module ContactFormHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
  
end

app/helpers/illustraions_helper.rb
module IllustraionsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/parallax_helper.rb
module ParallaxHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/parallax/home.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Keithmiketom Website</title>
		<%= stylesheet_link_tag    "normalize", :media => "all" %>
	  	<%= stylesheet_link_tag    "grid", :media => "all" %>
	  	<%= stylesheet_link_tag    "style", :media => "all" %>
	  	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>

	<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,600' rel='stylesheet' />

	</head>
	<body id="parallax">
		<div class="menu">
			<div class="container clearfix">
				<div id="logo" class="grid_2">
					<%=image_tag "homlogo.png"%>
				</div>
				<div id="nav" class="grid_10 omega">
					<ul class="navigation">
						<li data-slide="1">About Me</li>
						<li data-slide="2">About the Artwork</li>
						<li data-slide="3">Artwork</li>
						<li data-slide="6">Blog</li>
						<li data-slide="4">Developer</li>
						<li data-slide="5">Contact Me</li>
					</ul>
				</div>
			</div>
		</div>
		<div class="slide" id="slide1" data-slide="1" data-stellar-background-ratio="0.5">
			<div class="container clearfix">
				<div id="content" class="grid_7">
					<h1>Welcome to the city</h1> 
					<div class="building about"> 
						<h2><a href="about" title="about Keith">A Bit about me</a></h2>
						<p>Hi I'm Keith! I am an Artist, Designer, Illustrator, Educator, Web Developer and lover of Cats. I am from Dublin in Ireland. I Graduated from NCAD in 2006 with a BA in Art &amp; Design Education, with aspecialism in Graphic Design, though I always took a "Fine Art" methodology to my work
						<br /><br />In 2012 I returned to study Web Technologies in NCI part-time, building on my graphic design skills</p>
					</div>
				</div>
				<div id="decorative" class="grid_5 omega">
				
					<%=image_tag "bee.png", :class => "drag", :style => "width:300px" %>
					
				</div>
			</div>
		</div>
		<div class="slide" id="slide2" data-slide="2" data-stellar-background-ratio="0.5">
			<div class="container clearfix">
				<div class="art"> 
					<h2><a href="../galleries">About the Art</a></h2>
						<p>My work is a little bit quirky, and a lot of fun! I use an Illustrative style in all my approaches, and aim tomake anything I produce playful and fun to approach.</p>
						<p>I base some of my personal work on the world around me, whether it is interactions with others, past experiences, or the city I live in. I also paint cats and bees that shoot lasers from their eyes</p>
				</div>
			</div>
		</div>
		<div class="slide" id="slide3" data-slide="3" data-stellar-background-ratio="0.2">
			<div class="container clearfix">
				<div id="content" class="grid_12">
					<div id="gallery" class="content">
						<h2><%= link_to 'Artwork', galleries_path, :title => 'Art Gallery Link'%></h2>
						<hr />
							<div class="rm_wrapper">
								<div id="rm_container" class="rm_container">
									<ul>
										<li data-images="rm_container_1" data-rotation="-15"><%= image_tag "degreeshow/Ceramic.jpg", alt:"image1" %></li>
										<li data-images="rm_container_2" data-rotation="-5"><%= image_tag "catswithraybees/goldneko.jpg", alt:"image2" %></li>
										<li data-images="rm_container_3" data-rotation="5"><%= image_tag "illustration/army.jpg", alt:"image1" %></li>
										<li data-images="rm_container_4" data-rotation="15"><%= image_tag "catswithraybees/cheep.jpg", alt:"image1" %></li>
									</ul>
									<div id="rm_mask_left" class="rm_mask_left"></div>
									<div id="rm_mask_right" class="rm_mask_right"></div>
									<div id="rm_corner_left" class="rm_corner_left"></div>
									<div id="rm_corner_right" class="rm_corner_right"></div>
								<h2>Artwork</h2>
									<div style="display:none;">
										<div id="rm_container_1"><!--degree show-->
											<%= image_tag "degreeshow/dorris.jpg", alt:"image2" %>
											<%= image_tag "degreeshow/indifference.jpg", alt:"image3" %>
											<%= image_tag "degreeshow/Nostalgic.jpg", alt:"image4" %>
											<%= image_tag "degreeshow/Sweet.jpg", alt:"image4" %>
											<%= image_tag "degreeshow/Ceramic.jpg", alt:"image1" %>
											
										</div>
										<div id="rm_container_2"><!--raybees-->
											<%= image_tag "catswithraybees/Boobee.jpg", alt:"image2" %>
											<%= image_tag "catswithraybees/spacebbees.jpg", alt:"image3" %>
											<%= image_tag "catswithraybees/tim-curry.jpg", alt:"image4" %>
											<%= image_tag "catswithraybees/sr-wendy.jpg", alt:"image4", width:"350px" %>
											<%= image_tag "catswithraybees/goldneko.jpg", alt:"image1" %>
										
										</div>
										<div id="rm_container_3"><!--illustration Art-->
											<%= image_tag "illustration/Admit.jpg", alt:"image2" %>
											<%= image_tag "illustration/handjob.jpg", alt:"image3" %>
											<%= image_tag "illustration/paris.jpg", alt:"image4" %>
											<%= image_tag "illustration/bichonfrizz.jpg", alt:"image4" %>
											<%= image_tag "illustration/army.jpg", alt:"image1" %>
										</div>
										<div id="rm_container_4"><!--degree show-->
											<%= image_tag "catswithraybees/quenb.jpg", alt:"image2" %>
											<%= image_tag "catswithraybees/ray.jpg", alt:"image3" %>
											<%= image_tag "catswithraybees/vag.jpg", alt:"image4" %>
											<%= image_tag "catswithraybees/ray.jpg", alt:"image4" %>
											<%= image_tag "catswithraybees/cheep.jpg", alt:"image1" %>
										</div>
									</div>
								</div>
								<div class="rm_nav">
									<a id="rm_next" href="#" class="rm_next"></a>
									<a id="rm_prev" href="#" class="rm_prev"></a>
								</div>
								<div class="rm_controls">
									<a id="rm_play" href="#" class="rm_play">Play</a>
									<a id="rm_pause" href="#" class="rm_pause">Pause</a>
								</div>
							</div>
						</div>
				</div>
			</div>
		</div>
		</div>
		<div class="slide" id="slide6" data-slide="6" data-stellar-background-ratio="0.9">
			<div class="container clearfix">
				<div class="brokenbuilding">
					<h2><%= link_to 'Read my Blog', blogs_path, :title => 'blog link' %></h2>
				<p style="width:65%;color:white; text-align: justify; float:left;">
					I also write about what I do, whether it is Code Related (my developer hat), about Design or some Artworks I am working on. In any case, you can come and comment on what I am doing, and more importantly how I am doing, leaving suggestions and requests.
					</p>
					<%= image_tag "nav/SPEECH.png", alt:"speech bubble", style:"float:right;width:30%; margin-top:-170px;" %>
				</div>
			</div>
		</div>
		<div class="slide" id="slide4" data-slide="4" data-stellar-background-ratio="0.9">
			<div class="container clearfix">
				<div class="forgrnd"> 
					<h2>Developer</h2>
					<p>As well as Art &amp; design, I also Develop and make websites and web applications. Sometimes I will write about it in my blog. At the moment I love parallax scrolling, and I sometimes write about all the fun stuff I have learned.
					</p>
					
				</div><!--close fgd-->
				<div id="sky">
					<div id="bckgrnd">
						<div id="mdlgrnd">
							<div id="forgrnd">
							</div>
						</div>
					</div>
				</div>
			</div><!--close cnt clfx-->
		</div><!--close B C-->
		<div class="slide" id="slide5" data-slide="5" data-stellar-background-ratio="0.9">
			<div class="container clearfix">
				<div id="content" class="grid_12">
					
						<h2><%= link_to "Contact Keith", contact_path, :title =>"Contact me" %></h2>
						<p style="width:65%;color:white; text-align: justify;">Maybe you saw the site, maybe you like my work, maybe you want to get in touch and have me design make or develop something for you? maybe you just want cake? either way, fill in the form and I'll get in touch 
							</p>
						<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />
					
				</div><!--closeCntnt-->
			</div><!--close cnt clfx-->
		</div><!--close B C-->



<%= javascript_include_tag "jquery.easing.1.3" %>
<%= javascript_include_tag "waypoints.min" %>
<%= javascript_include_tag "jquery.stellar.min" %>
<%= javascript_include_tag "js" %>
<%= javascript_include_tag "parallax" %>
<%= javascript_include_tag "jquery-ui-1.10.2.custom.min" %>
<%= javascript_include_tag "jquery.transform-0.9.3.min_.js" %>
<%= javascript_include_tag "jquery.RotateImageMenu.js" %>
<%= javascript_include_tag "jquery.scrolling-parallax.js" %>
<script>
	
		$(".drag").draggable();
</script>
			</body>
</html>

app/views/parallax/homepage.html.erb
<!doctype html>
<html class="no-js" lang="en">
<head>
  <meta charset="utf-8">

  <title>keithmiketom.com</title>
  <meta name="description" content="Keithmiketom art and design portfolio">
  <meta name="author" content="Keith Gregg, Graphic Designer and Developer">

  <!-- Mmmmm, Google Web Fonts. That's a paddlin'. -->
  <link href='http://fonts.googleapis.com/css?family=Lobster+Two:700&v2' rel='stylesheet' type='text/css'>
 	<%= stylesheet_link_tag    "reset" %>
 	<%= stylesheet_link_tag    "parastyle" %>
	<%= stylesheet_link_tag    "style" %>

<body>

  <div id="main" role="main">

	<!-- Section #1 / Intro -->
	<section id="first" class="story" data-speed="8" data-type="background">    	
    
		<div class="introbit" data-type="sprite" data-offsetY="-300" data-Xposition="-10%" data-speed="-5"></div>		
		<article>

			<img src="/assets/bee.png" alt="intro-title"  />
			<p>Art Design and Illustration by Keith Gregg <br /> Twitter: <a href="http://twitter.com/keithmiketom" target="_blank">@keithmiketom</a> Web: <a href="http://keithgregg.com">keithgregg.com</a></p>
	    </article>
	</section>

	<!-- Section #2 / Background Only -->
	<section id="second" class="story" data-speed="4" data-type="background">
		<article>
        	<h1>Welcome to the City...</h1>
			<h2><a href="/about">A Bit about me</a></h2>
		    	<p>Hi I'm Keith! I am an Artist, Designer, Illustrator, Educator, Web Developer and lover of Cats. I am from Dublin in Ireland. I Graduated from NCAD in 2006 with a BA in Art & Design Education, with aspecialism in Graphic Design, though I always took a "Fine Art" methodology t my work. 

				<p>In 2012 I returned to study Web Technologies in NCI part-time, building on my graphic design skills.
		    	</p>		
		</article>
	</section>
    
    
	<!-- Section #3 / Web Developer -->
	<section id="third" class="story" data-speed="6" data-type="background" data-offsetY="250">    	
		<div class="photograph" data-type="sprite" data-offsetY="1250" data-Xposition="25%" data-speed="2"></div>
    	<article>
    		<h2><a href="/blogs">I Blog</a></h2>
	    	<div class="textbox">    	
		    	<p>I also write about what I do, whether it is Code Related (my developer hat), about Design or some Artworks I am working on. In any case, you can come and comment on what I am doing, and more importantly how I am doing, leaving suggestions and requests.</p>
		    </div>
    	</article>
	</section>	
    
    <!-- Section #4 / Gallery and Art bit -->
	<section id="fourth" class="story" data-speed="8" data-type="background" data-offsetY="250">
    	<article>
    		<h2 style="text-align: right;"> Art and the Gallery Bit</h2>
            
            
	    	<div class="textbox">    	
		    	<p>My work is a little bit quirky, and a lot of fun! I use an Illustrative style in all my approaches, and aim tomake anything I produce playful and fun to approach.

<br />I base some of my personal work on the world around me, whether it is interactions with others, past experiences, or the city I live in. I also paint cats and bees that shoot lasers from their eyes</p>
		    </div>
           <div id="gallery" class="content">
						<h2><%= link_to 'Artwork', galleries_path, :title => 'Art Gallery Link'%></h2>
						<hr />
							<div class="rm_wrapper">
								<div id="rm_container" class="rm_container">
									<ul>
										<li data-images="rm_container_1" data-rotation="-15"><%= image_tag "degreeshow/Ceramic.jpg", alt:"image1" %></li>
										<li data-images="rm_container_2" data-rotation="-5"><%= image_tag "catswithraybees/goldneko.jpg", alt:"image2" %></li>
										<li data-images="rm_container_3" data-rotation="5"><%= image_tag "illustration/army.jpg", alt:"image1" %></li>
										<li data-images="rm_container_4" data-rotation="15"><%= image_tag "catswithraybees/cheep.jpg", alt:"image1" %></li>
									</ul>
									<div id="rm_mask_left" class="rm_mask_left"></div>
									<div id="rm_mask_right" class="rm_mask_right"></div>
									<div id="rm_corner_left" class="rm_corner_left"></div>
									<div id="rm_corner_right" class="rm_corner_right"></div>
								<h2>Artwork</h2>
									<div style="display:none;">
										<div id="rm_container_1"><!--degree show-->
											<%= image_tag "degreeshow/dorris.jpg", alt:"image2" %>
											<%= image_tag "degreeshow/indifference.jpg", alt:"image3" %>
											<%= image_tag "degreeshow/Nostalgic.jpg", alt:"image4" %>
											<%= image_tag "degreeshow/Sweet.jpg", alt:"image4" %>
											<%= image_tag "degreeshow/Ceramic.jpg", alt:"image1" %>
											
										</div>
										<div id="rm_container_2"><!--raybees-->
											<%= image_tag "catswithraybees/Boobee.jpg", alt:"image2" %>
											<%= image_tag "catswithraybees/spacebbees.jpg", alt:"image3" %>
											<%= image_tag "catswithraybees/tim-curry.jpg", alt:"image4" %>
											<%= image_tag "catswithraybees/sr-wendy.jpg", alt:"image4", width:"350px" %>
											<%= image_tag "catswithraybees/goldneko.jpg", alt:"image1" %>
										
										</div>
										<div id="rm_container_3"><!--illustration Art-->
											<%= image_tag "illustration/Admit.jpg", alt:"image2" %>
											<%= image_tag "illustration/handjob.jpg", alt:"image3" %>
											<%= image_tag "illustration/paris.jpg", alt:"image4" %>
											<%= image_tag "illustration/bichonfrizz.jpg", alt:"image4" %>
											<%= image_tag "illustration/army.jpg", alt:"image1" %>
										</div>
										<div id="rm_container_4"><!--degree show-->
											<%= image_tag "catswithraybees/quenb.jpg", alt:"image2" %>
											<%= image_tag "catswithraybees/ray.jpg", alt:"image3" %>
											<%= image_tag "catswithraybees/vag.jpg", alt:"image4" %>
											<%= image_tag "catswithraybees/ray.jpg", alt:"image4" %>
											<%= image_tag "catswithraybees/cheep.jpg", alt:"image1" %>
										</div>
									</div>
								</div>
								<div class="rm_nav">
									<a id="rm_next" href="#" class="rm_next"></a>
									<a id="rm_prev" href="#" class="rm_prev"></a>
								</div>
								<div class="rm_controls">
									<a id="rm_play" href="#" class="rm_play">Play</a>
									<a id="rm_pause" href="#" class="rm_pause">Pause</a>
								</div>
							</div>
						</div>
    	</article>
	</section>
    
    	
    <!-- Section #3 / Blog -->
	<section id="fifth" class="story" data-speed="7" data-type="background">
		<article>
			<h2>Web Development</h2>
				<p>As well as Art &amp; design, I also Develop and make websites and web applications. Sometimes I will write about it in my blog. At the moment I love parallax scrolling, and I sometimes write about all the fun stuff I have learned.</p>	
		</article>
	</section>	
	
	

	<!-- Section #5 / Contact me!-->
	<section id="theend" class="story" data-speed="8" data-type="background" data-offsetY="250">    
    <article class="introbit">
    	<h2>Contact Me!</h2>
    	<p>Maybe you saw the site, maybe you like my work, maybe you want to get in touch and have me design make or develop something for you? maybe you just want cake?<br /> You can also see my design site,
    		keithgregg.com</p>
    </article>	
		<div class="byebye" data-type="sprite" data-offsetY="-2080" data-Xposition="50%" data-speed="-2"></div>	
   
	</section>
	
  </div> <!-- // End of #main -->




    <%= javascript_include_tag "jquery-1.6.1.min.js" %>
    <%= javascript_include_tag "script.js" %>
 	 <%= javascript_include_tag "jquery.transform-0.9.3.min_.js" %>
	<%= javascript_include_tag "jquery.RotateImageMenu.js" %>


</body>
</html>